#!/bin/bash

set -e

CFGFN=$1
MKCFG=../make_cfg
SAMPLER=sampler/target/release/midi_sample
LPXCTL=../target/release/lpx_ctl

for EXE in "${MKCFG}" "${SAMPLER}" "${LPXCTL}"; do
    if [[ ! -x "${EXE}" ]]; then
        echo "Error: '${EXE}' is not an executable file."
        exit 1
    fi
done

if [[ -z "${CFGFN}" ]]; then
    echo "Error: No configuration file specified."
    exit 1
fi

if [[ ! -r "${CFGFN}" ]]; then
    echo "Error: Cannot read file '${CFGFN}'."
    exit 1
fi

if  pgrep -f "${LPXCTL}" > /dev/null ; then
    echo " * kill  ${LPXCTL} "
    pkill -f ${LPXCTL}
fi

if  pgrep -f "${SAMPLER}" > /dev/null ; then
    echo " * kill  ${SAMPLER} "
    pkill -f ${SAMPLER}
fi

echo " * Start  ${LPXCTL} "
${MKCFG} "${CFGFN}" > "${CFGFN}.json"
${LPXCTL} "${CFGFN}.json" &

echo " * Start ${SAMPLER} "
${SAMPLER} drum_samples.json &

aconnect -l

